targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          include:
            - example/database.dart
      mockito|mockBuilder:
        generate_for:
          include:
            - 'test/mocks/**.dart'