name: drift_sentry
description: Sentry integration for the drift package.
version: 1.0.0
repository: https://github.com/utisam/drift_sentry/
issue_tracker: https://github.com/utisam/drift_sentry/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.8.2
  flutter:
    sdk: flutter
  meta: ^1.9.1
  mockito: ^5.4.2
  sentry: ^7.7.0
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.8.3
  build_runner: ^2.4.5
